services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_local
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dudes
      - POSTGRES_USER=dudes
      - POSTGRES_DB=dudes

volumes:
  postgres-data:
